name: docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - run: deno task start
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./pages
      - uses: actions/deploy-pages@v1
        id: deployment
